# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "1efc71538fd9ed688ee7ebf794951570"
name = "testing"
handle = "testing-1308"
application_url = "https://aw-pace-outline-developing.trycloudflare.com/"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "vrmeditech.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_inventory,write_products"

[auth]
redirect_urls = [
  "https://aw-pace-outline-developing.trycloudflare.com/auth/callback",
  "https://aw-pace-outline-developing.trycloudflare.com/auth/shopify/callback",
  "https://aw-pace-outline-developing.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-10"

[pos]
embedded = false
